set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

set(CMAKE_C_COMPILER   ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_RC_COMPILER  ${TOOLCHAIN_PREFIX}-windres)

# Cross-compiled deps installed via setup-mingw-deps.sh
if(NOT DEFINED MINGW_DEPS_DIR)
	set(MINGW_DEPS_DIR "$ENV{HOME}/mingw-deps")
endif()

# CRITICAL: Include deps dir in FIND_ROOT_PATH so find_library/find_path work
set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX} "${MINGW_DEPS_DIR}")
list(APPEND CMAKE_PREFIX_PATH "${MINGW_DEPS_DIR}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(ENV{PKG_CONFIG_PATH} "${MINGW_DEPS_DIR}/lib/pkgconfig")
